

select distinct DEGREE_INJURY from accidents;

select * from accidents where DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY');

select * from accidents where DEGREE_INJURY in ('INJURIES INVOLVNG NONEMPLOYEES', 'ACCIDENT ONLY', 'NO DYS AWY FRM WRK,NO RSTR ACT');

select * from accidents where DEGREE_INJURY in ('OCCUPATNAL ILLNESS NOT DEG 1-6','DYS AWY FRM WRK & RESTRCTD ACT', 'ALL OTHER CASES (INCL 1ST AID)');



select * from (select * from accidents where DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY')) A, (select * from accidents where DEGREE_INJURY in ('INJURIES INVOLVNG NONEMPLOYEES', 'ACCIDENT ONLY', 'NO DYS AWY FRM WRK,NO RSTR ACT','OCCUPATNAL ILLNESS NOT DEG 1-6','DYS AWY FRM WRK & RESTRCTD ACT', 'ALL OTHER CASES (INCL 1ST AID)')) B where A.MINE_ID = B.MINE_ID;

select * from accidents where DEGREE_INJURY in ('INJURIES INVOLVNG NONEMPLOYEES', 'ACCIDENT ONLY', 'NO DYS AWY FRM WRK,NO RSTR ACT','OCCUPATNAL ILLNESS NOT DEG 1-6','DYS AWY FRM WRK & RESTRCTD ACT', 'ALL OTHER CASES (INCL 1ST AID)') and MINE_ID in (select MINE_ID from accidents where DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY'));

select * from violations where EVENT_NO in (select EVENT_NO from inspections where MINE_ID in (select MINE_ID from accidents where DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY'))); 

select * from mines LIMIT 100;

select count(*) from violations v, inspections i, accidents a, mines m where 
v.EVENT_NO = i.EVENT_NO and 
v.MINE_ID = a.MINE_ID and 
a.MINE_ID = m.MINE_ID and 
a.DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY') and 
m.CURRENT_MINE_STATUS NOT IN ('New Mine');
select distinct CURRENT_MINE_STATUS from mines;

select a.MINE_ID from accidents a, mines m where DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY') and m.CURRENT_MINE_STATUS = 'Active' and m.MINE_ID = a.MINE_ID; 

select * from violations where EVENT_NO in (select EVENT_NO from inspections where MINE_ID in (select a.MINE_ID from accidents a, mines m where DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY') and m.CURRENT_MINE_STATUS = 'Active' and m.MINE_ID = a.MINE_ID)); 


select * 
from violations v, inspections i, accidents a, mines m where 
v.EVENT_NO = i.EVENT_NO and 
v.MINE_ID = a.MINE_ID and 
a.MINE_ID = m.MINE_ID and 
a.DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY') and 
m.CURRENT_MINE_STATUS NOT IN ('New Mine') and
STR_TO_DATE(i.INSPECTION_END_DT, '%m/%d/%Y') < STR_TO_DATE(a.ACCIDENT_DT, '%m/%d/%Y');


SELECT v.VIOLATOR_TYPE_CD,v.MINE_TYPE,v.COAL_METAL_IND,v.SIG_SUB,v.LIKELIHOOD,v.INJ_ILLNESS,v.NO_AFFECTED,v.NEGLIGENCE,v.SPECIAL_ASSESS,v.PRIMARY_OR_MILL,v.ASMT_GENERATED_IND,	v.CONTESTED_IND,v.VIOLATOR_VIOLATION_CNT,v.VIOLATOR_INSPECTION_DAY_CNT,i.ACTIVITY,i.ACTIVE_SECTIONS,i.IDLE_SECTIONS,i.SHAFT_SLOPE_SINK,i.IMPOUND_CONSTR,i.BLDG_CONSTR_SITES,i.DRAGLINES,i.UNCLASSIFIED_CONSTR,i.CO_RECORDS,i.SURF_UG_MINE,i.SURF_FACILITY_MINE,i.REFUSE_PILES,i.EXPLOSIVE_STORAGE,i.OUTBY_AREAS,i.MAJOR_CONSTR,i.SHAFTS_SLOPES,i.IMPOUNDMENTS,i.MISC_AREA,i.PROGRAM_AREA,i.SAMPLE_CNT_AIR,i.SAMPLE_CNT_DUSTSPOT,i.SAMPLE_CNT_DUSTSURVEY,i.SAMPLE_CNT_RESPDUST,i.SAMPLE_CNT_NOISE,i.SAMPLE_CNT_OTHER	NBR_INSPECTORS,i.TOTAL_ON_SITE_HOURS,i.TOTAL_INSP_HOURS,i.COAL_METAL_IND,i.TOTAL_ON_SITE_HRS_SPVR_TRAINEE,i.TOTAL_INSP_HRS_SPVR_TRAINEE,a.MINING_EQUIP_CD,a.MINING_EQUIP,a.EQUIP_MFR_NAME,a.CLASSIFICATION,a.ACCIDENT_TYPE_CD,a.ACCIDENT_TYPE,a.TOT_EXPER,a.MINE_EXPER,a.JOB_EXPER,a.OCCUPATION_CD,a.OCCUPATION,a.ACTIVITY,a.INJURY_SOURCE,m.PRIMARY_SIC,m.PRIMARY_CANVASS,m.PORTABLE_OPERATION,m.PORTABLE_FIPS_ST_CD,m.DAYS_PER_WEEK,m.HOURS_PER_SHIFT,m.PROD_SHIFTS_PER_DAY,m.MAINT_SHIFTS_PER_DAY,m.NO_EMPLOYEES,m.PART48_TRAINING,m.AVG_MINE_HEIGHT,m.PILLAR_RECOVERY_USED,m.HIGHWALL_MINER_USED,m.MULTIPLE_PITS

SELECT v.VIOLATOR_TYPE_CD,v.MINE_TYPE,v.COAL_METAL_IND,v.SIG_SUB,v.LIKELIHOOD,v.INJ_ILLNESS,v.NO_AFFECTED,v.NEGLIGENCE,v.SPECIAL_ASSESS,v.PRIMARY_OR_MILL,v.ASMT_GENERATED_IND,	v.CONTESTED_IND,v.VIOLATOR_VIOLATION_CNT,v.VIOLATOR_INSPECTION_DAY_CNT,i.ACTIVITY,i.ACTIVE_SECTIONS,i.IDLE_SECTIONS,i.SHAFT_SLOPE_SINK,i.IMPOUND_CONSTR,i.BLDG_CONSTR_SITES,i.DRAGLINES,i.UNCLASSIFIED_CONSTR,i.CO_RECORDS,i.SURF_UG_MINE,i.SURF_FACILITY_MINE,i.REFUSE_PILES,i.EXPLOSIVE_STORAGE,i.OUTBY_AREAS,i.MAJOR_CONSTR,i.SHAFTS_SLOPES,i.IMPOUNDMENTS,i.MISC_AREA,i.PROGRAM_AREA,i.SAMPLE_CNT_AIR,i.SAMPLE_CNT_DUSTSPOT,i.SAMPLE_CNT_DUSTSURVEY,i.SAMPLE_CNT_RESPDUST,i.SAMPLE_CNT_NOISE,i.SAMPLE_CNT_OTHER,i.NBR_INSPECTORS,i.TOTAL_ON_SITE_HOURS,i.TOTAL_INSP_HOURS,i.COAL_METAL_IND,i.TOTAL_ON_SITE_HRS_SPVR_TRAINEE,i.TOTAL_INSP_HRS_SPVR_TRAINEE,m.PRIMARY_SIC,m.PRIMARY_CANVASS,m.PORTABLE_OPERATION,m.PORTABLE_FIPS_ST_CD,m.DAYS_PER_WEEK,m.HOURS_PER_SHIFT,m.PROD_SHIFTS_PER_DAY,m.MAINT_SHIFTS_PER_DAY,m.NO_EMPLOYEES,m.PART48_TRAINING,m.AVG_MINE_HEIGHT,m.PILLAR_RECOVERY_USED,m.HIGHWALL_MINER_USED,m.MULTIPLE_PITS
from violations v, inspections i, accidents a, mines m where 
v.EVENT_NO = i.EVENT_NO and 
v.MINE_ID = a.MINE_ID and 
a.MINE_ID = m.MINE_ID and 
a.DEGREE_INJURY IN('PERM TOT OR PERM PRTL DISABLTY','FATALITY') and 
m.CURRENT_MINE_STATUS NOT IN ('New Mine') and
STR_TO_DATE(i.INSPECTION_END_DT, '%m/%d/%Y') < STR_TO_DATE(a.ACCIDENT_DT, '%m/%d/%Y');



SELECT v.VIOLATOR_TYPE_CD,v.MINE_TYPE,v.COAL_METAL_IND,v.SIG_SUB,v.LIKELIHOOD,v.INJ_ILLNESS,v.NO_AFFECTED,v.NEGLIGENCE,v.SPECIAL_ASSESS,v.PRIMARY_OR_MILL,v.ASMT_GENERATED_IND,	v.CONTESTED_IND,v.VIOLATOR_VIOLATION_CNT,v.VIOLATOR_INSPECTION_DAY_CNT,i.ACTIVITY,i.ACTIVE_SECTIONS,i.IDLE_SECTIONS,i.SHAFT_SLOPE_SINK,i.IMPOUND_CONSTR,i.BLDG_CONSTR_SITES,i.DRAGLINES,i.UNCLASSIFIED_CONSTR,i.CO_RECORDS,i.SURF_UG_MINE,i.SURF_FACILITY_MINE,i.REFUSE_PILES,i.EXPLOSIVE_STORAGE,i.OUTBY_AREAS,i.MAJOR_CONSTR,i.SHAFTS_SLOPES,i.IMPOUNDMENTS,i.MISC_AREA,i.PROGRAM_AREA,i.SAMPLE_CNT_AIR,i.SAMPLE_CNT_DUSTSPOT,i.SAMPLE_CNT_DUSTSURVEY,i.SAMPLE_CNT_RESPDUST,i.SAMPLE_CNT_NOISE,i.SAMPLE_CNT_OTHER,i.NBR_INSPECTORS,i.TOTAL_ON_SITE_HOURS,i.TOTAL_INSP_HOURS,i.COAL_METAL_IND,i.TOTAL_ON_SITE_HRS_SPVR_TRAINEE,i.TOTAL_INSP_HRS_SPVR_TRAINEE,m.PRIMARY_SIC,m.PRIMARY_CANVASS,m.PORTABLE_OPERATION,m.PORTABLE_FIPS_ST_CD,m.DAYS_PER_WEEK,m.HOURS_PER_SHIFT,m.PROD_SHIFTS_PER_DAY,m.MAINT_SHIFTS_PER_DAY,m.NO_EMPLOYEES,m.PART48_TRAINING,m.AVG_MINE_HEIGHT,m.PILLAR_RECOVERY_USED,m.HIGHWALL_MINER_USED,m.MULTIPLE_PITS
from violations v, inspections i, mines m where 
v.EVENT_NO = i.EVENT_NO and 
v.MINE_ID not in ( select distinct MINE_ID from accidents) and
v.MINE_ID = m.MINE_ID and 
m.CURRENT_MINE_STATUS IN ('New Mine');



SELECT i.MINE_ID, v.VIOLATOR_TYPE_CD,v.MINE_TYPE,v.COAL_METAL_IND,v.SIG_SUB,v.LIKELIHOOD,v.INJ_ILLNESS,v.NO_AFFECTED,v.NEGLIGENCE,v.SPECIAL_ASSESS,v.PRIMARY_OR_MILL,v.ASMT_GENERATED_IND,	v.CONTESTED_IND,v.VIOLATOR_VIOLATION_CNT,v.VIOLATOR_INSPECTION_DAY_CNT,i.ACTIVITY,i.ACTIVE_SECTIONS,i.IDLE_SECTIONS,i.SHAFT_SLOPE_SINK,i.IMPOUND_CONSTR,i.BLDG_CONSTR_SITES,i.DRAGLINES,i.UNCLASSIFIED_CONSTR,i.CO_RECORDS,i.SURF_UG_MINE,i.SURF_FACILITY_MINE,i.REFUSE_PILES,i.EXPLOSIVE_STORAGE,i.OUTBY_AREAS,i.MAJOR_CONSTR,i.SHAFTS_SLOPES,i.IMPOUNDMENTS,i.MISC_AREA,i.PROGRAM_AREA,i.SAMPLE_CNT_AIR,i.SAMPLE_CNT_DUSTSPOT,i.SAMPLE_CNT_DUSTSURVEY,i.SAMPLE_CNT_RESPDUST,i.SAMPLE_CNT_NOISE,i.SAMPLE_CNT_OTHER,i.NBR_INSPECTORS,i.TOTAL_ON_SITE_HOURS,i.TOTAL_INSP_HOURS,i.COAL_METAL_IND,i.TOTAL_ON_SITE_HRS_SPVR_TRAINEE,i.TOTAL_INSP_HRS_SPVR_TRAINEE,m.PRIMARY_SIC,m.PRIMARY_CANVASS,m.PORTABLE_OPERATION,m.PORTABLE_FIPS_ST_CD,m.DAYS_PER_WEEK,m.HOURS_PER_SHIFT,m.PROD_SHIFTS_PER_DAY,m.MAINT_SHIFTS_PER_DAY,m.NO_EMPLOYEES,m.PART48_TRAINING,m.AVG_MINE_HEIGHT,m.PILLAR_RECOVERY_USED,m.HIGHWALL_MINER_USED,m.MULTIPLE_PITS
from inspections i, mines m, violations v where i.MINE_ID = m.MINE_ID and m.CURRENT_MINE_STATUS ='New Mine' and v.EVENT_NO = i.EVENT_NO;

