create database mining;


use mining;

CREATE TABLE `accidents` (  `MINE_ID` varchar(255),
  `CONTROLLER_ID` varchar(255),
  `CONTROLLER_NAME` varchar(255),
  `OPERATOR_ID` varchar(255),
  `OPERATOR_NAME` varchar(255),
  `CONTRACTOR_ID` varchar(255),
  `DOCUMENT_NO` varchar(255),
  `SUBUNIT_CD` varchar(255),
  `SUBUNIT` varchar(255),
  `ACCIDENT_DT` varchar(255),
  `CAL_YR` varchar(255),
  `CAL_QTR` varchar(255),
  `FISCAL_YR` varchar(255),
  `FISCAL_QTR` varchar(255),
  `ACCIDENT_TIME` varchar(255),
  `DEGREE_INJURY_CD` varchar(255),
  `DEGREE_INJURY` varchar(255),
  `FIPS_STATE_CD` varchar(255),
  `UG_LOCATION_CD` varchar(255),
  `UG_LOCATION` varchar(255),
  `UG_MINING_METHOD_CD` varchar(255),
  `UG_MINING_METHOD` varchar(255),
  `MINING_EQUIP_CD` varchar(255),
  `MINING_EQUIP` varchar(255),
  `EQUIP_MFR_CD` varchar(255),
  `EQUIP_MFR_NAME` varchar(255),
  `EQUIP_MODEL_NO` varchar(255),
  `SHIFT_BEGIN_TIME` varchar(255),
  `CLASSIFICATION_CD` varchar(255),
  `CLASSIFICATION` varchar(255),
  `ACCIDENT_TYPE_CD` varchar(255),
  `ACCIDENT_TYPE` varchar(255),
  `NO_INJURIES` varchar(255),
  `TOT_EXPER` varchar(255),
  `MINE_EXPER` varchar(255),
  `JOB_EXPER` varchar(255),
  `OCCUPATION_CD` varchar(255),
  `OCCUPATION` varchar(255),
  `ACTIVITY_CD` varchar(255),
  `ACTIVITY` varchar(255),
  `INJURY_SOURCE_CD` varchar(255),
  `INJURY_SOURCE` varchar(255),
  `NATURE_INJURY_CD` varchar(255),
  `NATURE_INJURY` varchar(255),
  `INJ_BODY_PART_CD` varchar(255),
  `INJ_BODY_PART` varchar(255),
  `SCHEDULE_CHARGE` varchar(255),
  `DAYS_RESTRICT` varchar(255),
  `DAYS_LOST` varchar(255),
  `TRANS_TERM` varchar(255),
  `RETURN_TO_WORK_DT` varchar(255),
  `IMMED_NOTIFY_CD` varchar(255),
  `IMMED_NOTIFY` varchar(255),
  `INVEST_BEGIN_DT` varchar(255),
  `NARRATIVE` varchar(255),
  `CLOSED_DOC_NO` varchar(255),
  `COAL_METAL_IND` varchar(255),
 PRIMARY KEY (`MINE_ID`) 
) ENGINE=InnoDB AUTO_INCREMENT=5506 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

LOAD DATA LOCAL INFILE 'Accidents.txt' INTO TABLE accidents
  FIELDS TERMINATED BY '|'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES;
  
CREATE TABLE `inspections` (  `ÏEVENT_NO` varchar(255),
  `MINE_ID` varchar(255),
  `INSPECTION_BEGIN_DT` varchar(255),
  `INSPECTION_END_DT` varchar(255),
  `CONTROLLER_ID` varchar(255),
  `CONTROLLER_NAME` varchar(255),
  `OPERATOR_ID` varchar(255),
  `OPERATOR_NAME` varchar(255),
  `CAL_YR` varchar(255),
  `CAL_QTR` varchar(255),
  `FISCAL_YR` varchar(255),
  `FISCAL_QTR` varchar(255),
  `INSPECT_OFFICE_CD` varchar(255),
  `ACTIVITY_CODE` varchar(255),
  `ACTIVITY` varchar(255),
  `ACTIVE_SECTIONS` varchar(255),
  `IDLE_SECTIONS` varchar(255),
  `SHAFT_SLOPE_SINK` varchar(255),
  `IMPOUND_CONSTR` varchar(255),
  `BLDG_CONSTR_SITES` varchar(255),
  `DRAGLINES` varchar(255),
  `UNCLASSIFIED_CONSTR` varchar(255),
  `CO_RECORDS` varchar(255),
  `SURF_UG_MINE` varchar(255),
  `SURF_FACILITY_MINE` varchar(255),
  `REFUSE_PILES` varchar(255),
  `EXPLOSIVE_STORAGE` varchar(255),
  `OUTBY_AREAS` varchar(255),
  `MAJOR_CONSTR` varchar(255),
  `SHAFTS_SLOPES` varchar(255),
  `IMPOUNDMENTS` varchar(255),
  `MISC_AREA` varchar(255),
  `PROGRAM_AREA` varchar(255),
  `SUM(SAMPLE_CNT_AIR)` varchar(255),
  `SUM(SAMPLE_CNT_DUSTSPOT)` varchar(255),
  `SUM(SAMPLE_CNT_DUSTSURVEY)` varchar(255),
  `SUM(SAMPLE_CNT_RESPDUST)` varchar(255),
  `SUM(SAMPLE_CNT_NOISE)` varchar(255),
  `SUM(SAMPLE_CNT_OTHER)` varchar(255),
  `NBR_INSPECTOR` varchar(255),
  `SUM(TOTAL_INSP_HOURS)` varchar(255),
  `SUM(TOTAL_ON_SITE_HOURS)` varchar(255),
  `COAL_METAL_IND` varchar(255),
  `SUM(TOTAL_INSP_HRS_SPVR_TRAINEE)` varchar(255),
  `SUM(TOTAL_ON_SITE_HRS_SPVR_TRAINEE)` varchar(255),
   PRIMARY KEY (`ÏEVENT_NO`)
 ) ENGINE=InnoDB AUTO_INCREMENT=5506 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
 

LOAD DATA LOCAL INFILE 'Inspections.txt' INTO TABLE inspections
  FIELDS TERMINATED BY '|'
  LINES TERMINATED BY '\r\n'
  IGNORE 1 LINES;